engines:
  credo:
    enabled: true
    channel: "beta"
  eslint:
    enabled: true
  csslint:
    enabled: true
    exclude_paths:
      - "web/static/css/phoenix.css"
  fixme:
    enabled: true
ratings:
  paths:
    - "**.ex"
    - "**.exs"
    - "**.js"
    - "**.css"
